name: Event triggered demo workflow
on: 
  pull_request:
    types: [opened, synchronize, reopened] ## activity types filtros por tipo de atividade pode enviar lista ou apenas um tipo
  push:
    branches: [ main, dev ] ##filtro por ramas
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ github.event_name }}"

      - name: Get code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Test code
        run: |
          npm run Lint
          npm run test  
          
      - name: Build code
        run: |
          npm run build
          echo " HEADDd - ${{ github.head_ref }}"
          
      - name: Deploy project
        run: echo "Deploying..."