name: Event triggered demo workflow
on: 
  pull_request:
    types: [opened, reopened] ## activity types filtros por tipo de atividade pode enviar lista ou apenas um tipo
  push:
    branches: [ main, dev ] ##filtro por ramas
    paths-ignore:
      - 'workflow/uso-pratico.yml'  ##ignorar mudan√ßas em uso-pratico
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ github.event_name }}"

      - name: Get code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Test code
        run:  npm run test  

      - name: Build code
        run: |
          npm run build
          echo " HEADDd - ${{ github.head_ref }}"
          
      - name: Deploy project
        run: echo "Deploying..."