name: Uso de Variáveis de Entrada
on:
    workflow_call:
        inputs:
            nome:
                description: 'Nome da pessoa'
                required: true
                type: string
            idade:
                description: 'Idade da pessoa'
                required: true
                type: number
jobs:
    exibir-variaveis:
        if: contains(github.actor, 'dev')
        runs-on: ubuntu-latest
        outputs:
            idade-saida:  ${{ steps.exibir.outputs.idade-saida }} ##define a idade de saída do job como o valor do input idade convertido para número
        steps:
            - name: exibir nome e idade
              id: exibir
              run: |
                echo "Nome: ${{ github.actor }} + ${{ inputs.nome }}"
                echo "Idade: ${{ inputs.idade }}"
                echo "idade-saida=$((${{ inputs.idade }} + 5))" >> $GITHUB_OUTPUT

    exibir-idade-saida:
        needs: exibir-variaveis
        runs-on: ubuntu-latest
        steps:
            - name: mostrar idade de saida do job anterior
              run: |
                echo "Idade de saída do job anterior: ${{ needs.exibir-variaveis.outputs.idade-saida }}"

                